import { TRPCReactProvider } from "@/trpc/client";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getLocale } from "next-intl/server";
import { DM_Sans } from "next/font/google";
import { Toaster } from "sonner";
import { NuqsAdapter } from "nuqs/adapters/next/app";

import "./globals.css";

const dmSans = DM_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const dir = locale === "ar" ? "rtl" : "ltr";

  return (
    <html lang={locale} dir={dir}>
      <NextIntlClientProvider>
        <body className={`${dmSans.className} antialiased`}>
          <NuqsAdapter>
            <TRPCReactProvider>
              {children}
              <Toaster />
            </TRPCReactProvider>
          </NuqsAdapter>
        </body>
      </NextIntlClientProvider>
    </html>
  );
}
