import { TRPCReactProvider } from "@/trpc/client";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getLocale } from "next-intl/server";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { getQueryClient, trpc } from "@/trpc/server";

const dmSans = DM_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const dir = locale === "ar" ? "rtl" : "ltr";

  const queryClient = getQueryClient();
  const x = await queryClient.fetchQuery(
    trpc.categories.getMany.queryOptions()
  );

  console.log({ x });
  return (
    <html lang={locale} dir={dir}>
      <NextIntlClientProvider>
        <body className={`${dmSans.className} antialiased`}>
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </body>
      </NextIntlClientProvider>
    </html>
  );
}
