import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { getLocale } from "next-intl/server";

const dmSans = DM_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const dir = locale === "ar" ? "rtl" : "ltr";
  return (
    <html lang={locale} dir={dir}>
      <body className={`${dmSans.className} antialiased`}>{children}</body>
    </html>
  );
}
